version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: 'nginx-proxy'
    restart: always
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"